import {
  ArrowRightLeft,
  BookText,
  Building2,
  CalendarCheck2,
  FileText,
  FlaskConical,
  Home as HomeIcon,
  Hotel,
  Landmark,
  MapPinned,
  Microscope,
  Package,
  Pill,
  Settings,
  ShieldPlus,
  Stethoscope,
  UserRound,
  Users,
  WalletCards,
} from "lucide-react";

import { BedIcon } from "./bed-icon";
import { hospitalSystemBlueprint } from "./hospital-static-data";

const workflow = [
  "Login and role check",
  "Select module from menu",
  "Use static list or table",
  "Open detail section",
  "Move to billing or report",
];

export const moduleConfigs = {
  modules: {
    title: "Modules Overview",
    subtitle: "A static roadmap of the full hospital system flow.",
    icon: Building2,
    tone: "bg-[#dbeafe]",
    systemOverview: hospitalSystemBlueprint.systemOverview,
    stats: [
      { label: "Core Modules", value: "18", note: "active menu items" },
      { label: "Workflow Stages", value: "5", note: "static flow steps" },
      { label: "Protected Session", value: "1", note: "demo admin user" },
    ],
    columns: ["Module", "Purpose", "Status"],
    rows: [
      ["Dashboard", "Overview cards and KPIs", "Ready"],
      ["Patient", "Registry and admission queue", "Ready"],
      ["Doctor", "Roster and consultation list", "Ready"],
      ["Appointment", "Slot booking flow", "Ready"],
      ["Finance", "Collections and balances", "Ready"],
    ],
    notes: workflow,
  },
  pathology: {
    title: "Pathology",
    subtitle: "Lab requisitions, pending tests, and report-ready samples.",
    icon: Microscope,
    tone: "bg-[#fee2e2]",
    stats: [
      { label: "Samples Today", value: "24", note: "collected" },
      { label: "Pending Reports", value: "7", note: "awaiting review" },
      { label: "Urgent Tests", value: "3", note: "priority cases" },
    ],
    columns: ["Test", "Patient", "Status"],
    rows: [
      ["CBC", "Rahim Uddin", "Collected"],
      ["CRP", "Nasrin Akter", "In progress"],
      ["Blood Group", "Mim Akter", "Ready"],
      ["Urine R/E", "Arif Hossain", "Pending"],
    ],
    notes: ["Sample registration", "Machine processing", "Doctor review", "Report delivery"],
  },
  radiology: {
    title: "Radiology",
    subtitle: "Scan queue, imaging review, and report handoff.",
    icon: FlaskConical,
    tone: "bg-[#ede9fe]",
    stats: [
      { label: "Scans Today", value: "12", note: "x-ray / ultrasound" },
      { label: "Waiting Review", value: "4", note: "radiologist queue" },
      { label: "Completed", value: "8", note: "released reports" },
    ],
    columns: ["Scan", "Patient", "Status"],
    rows: [
      ["X-Ray Chest", "Hasan Ali", "Completed"],
      ["USG Abdomen", "Tania Sultana", "Review"],
      ["CT Head", "Jahid Khan", "Queued"],
      ["MRI Spine", "Sadia Noor", "Scheduled"],
    ],
    notes: ["Booking", "Scan capture", "Report drafting", "Delivery"],
  },
  appointment: {
    title: "Appointment",
    subtitle: "A simple static booking queue for patient consultation.",
    icon: CalendarCheck2,
    tone: "bg-[#dcfce7]",
    actions: ["New booking", "Check slot", "Confirm visit", "Move to OPD"],
    stats: [
      { label: "Booked", value: "18", note: "today" },
      { label: "Waiting", value: "6", note: "in lobby" },
      { label: "Completed", value: "11", note: "seen by doctor" },
    ],
    formTitle: "Main Entry Form",
    formFields: hospitalSystemBlueprint.appointment.formFields,
    relations: hospitalSystemBlueprint.appointment.relations,
    entrySteps: hospitalSystemBlueprint.appointment.entrySteps,
    slotBoard: hospitalSystemBlueprint.appointment.slotBoard,
    queueSummary: hospitalSystemBlueprint.appointment.queues,
    columns: ["Time", "Patient", "Doctor"],
    rows: [
      ["09:30", "Ayesha", "Dr. Rahman"],
      ["10:00", "Imran", "Dr. Karim"],
      ["10:30", "Nabila", "Dr. Sultana"],
      ["11:00", "Rafi", "Dr. Hasan"],
    ],
    notes: ["Select doctor", "Assign time", "Confirm patient", "Move to OPD"],
    board: [
      { label: "Morning", items: ["09:00 OPD-12", "09:30 OPD-13", "10:00 OPD-14"] },
      { label: "Midday", items: ["11:00 OPD-15", "11:30 OPD-16", "12:00 OPD-17"] },
      { label: "Evening", items: ["03:00 OPD-18", "03:30 OPD-19", "04:00 OPD-20"] },
    ],
    summary: [
      { label: "Next slot", value: "09:30 AM" },
      { label: "Queue room", value: "OPD Lobby" },
      { label: "Consultant", value: "Dr. Rahman" },
    ],
  },
  opd: {
    title: "OPD",
    subtitle: "Outpatient visit flow with token and consultation steps.",
    icon: Stethoscope,
    tone: "bg-[#dbeafe]",
    stats: [
      { label: "Tokens Issued", value: "31", note: "today" },
      { label: "Consulted", value: "22", note: "done" },
      { label: "Waiting", value: "9", note: "queue" },
    ],
    columns: ["Token", "Patient", "Doctor"],
    rows: [
      ["OPD-01", "Sumon", "Dr. Karim"],
      ["OPD-02", "Tithi", "Dr. Hasan"],
      ["OPD-03", "Sabbir", "Dr. Rahman"],
      ["OPD-04", "Mou", "Dr. Sultana"],
    ],
    notes: ["Token issue", "Vitals entry", "Doctor consult", "Billing"],
  },
  ipd: {
    title: "IPD",
    subtitle: "Inpatient admissions, beds, and discharge tracking.",
    icon: Hotel,
    tone: "bg-[#cffafe]",
    stats: [
      { label: "Occupied Beds", value: "10", note: "of 14" },
      { label: "Admitted", value: "8", note: "active cases" },
      { label: "Discharged", value: "2", note: "today" },
    ],
    columns: ["Bed", "Patient", "Ward"],
    rows: [
      ["B-01", "Mahin", "Male Ward"],
      ["B-04", "Jannat", "Female Ward"],
      ["B-06", "Shuvo", "Surgery"],
      ["B-09", "Ritu", "Cabin"],
    ],
    notes: ["Admission", "Bed assignment", "Daily rounds", "Discharge summary"],
  },
  ambulance: {
    title: "Ambulance",
    subtitle: "Static dispatch queue for emergency transport requests.",
    icon: MapPinned,
    tone: "bg-[#ffedd5]",
    stats: [
      { label: "Active Trips", value: "3", note: "on route" },
      { label: "Pending Calls", value: "2", note: "waiting" },
      { label: "Available", value: "1", note: "ready vehicle" },
    ],
    columns: ["Trip", "Location", "Status"],
    rows: [
      ["AMB-01", "Uttara", "On route"],
      ["AMB-02", "Mirpur", "Returning"],
      ["AMB-03", "Dhanmondi", "Dispatched"],
      ["AMB-04", "Gulshan", "Pending"],
    ],
    notes: ["Call received", "Nearest vehicle", "Trip tracking", "Return to base"],
  },
  blood: {
    title: "Blood Bank",
    subtitle: "Blood availability, donor status, and request handling.",
    icon: ShieldPlus,
    tone: "bg-[#fee2e2]",
    stats: [
      { label: "Units Available", value: "48", note: "in stock" },
      { label: "Donors", value: "22", note: "registered" },
      { label: "Requests", value: "6", note: "pending" },
    ],
    columns: ["Group", "Units", "Status"],
    rows: [
      ["A+", "12", "Healthy"],
      ["B+", "8", "Healthy"],
      ["O+", "18", "Low"],
      ["AB+", "10", "Healthy"],
    ],
    notes: ["Donor registration", "Blood test", "Issue request", "Dispatch"],
  },
  pharmacy: {
    title: "Pharmacy",
    subtitle: "Prescription queue and medicine dispensing flow.",
    icon: Pill,
    tone: "bg-[#fef3c7]",
    stats: [
      { label: "Prescriptions", value: "19", note: "today" },
      { label: "Dispensed", value: "15", note: "completed" },
      { label: "Short Stock", value: "4", note: "alerts" },
    ],
    columns: ["Medicine", "Qty", "Status"],
    rows: [
      ["Napa", "120", "Ready"],
      ["Cefixime", "42", "Low"],
      ["ORS", "90", "Ready"],
      ["Amlodipine", "18", "Reorder"],
    ],
    notes: ["Prescription check", "Stock verify", "Dispense", "Invoice"],
  },
  medicine: {
    title: "Medicine",
    subtitle: "Product inventory and expiry monitoring.",
    icon: Package,
    tone: "bg-[#e0e7ff]",
    stats: [
      { label: "Total Items", value: "142", note: "catalogued" },
      { label: "Expired", value: "4", note: "remove now" },
      { label: "Reorder", value: "11", note: "items" },
    ],
    columns: ["Item", "Stock", "Expiry"],
    rows: [
      ["Napa 500", "320", "Dec 2026"],
      ["Syrup", "56", "Sep 2026"],
      ["Antacid", "24", "Aug 2026"],
      ["Insulin", "12", "Jun 2026"],
    ],
    notes: ["Receive stock", "Batch entry", "Expiry tracking", "Reorder alert"],
  },
  finance: {
    title: "Finance",
    subtitle: "Cash, bank, and collections snapshot for the day.",
    icon: WalletCards,
    tone: "bg-[#c7d2fe]",
    actions: ["Open cashbook", "Add payment", "Close day", "Export report"],
    stats: [
      { label: "Cash Balance", value: "24,820", note: "today" },
      { label: "Bank Balance", value: "0", note: "linked later" },
      { label: "Collections", value: "7,400", note: "total today" },
    ],
    columns: ["Source", "Amount", "Status"],
    rows: [
      ["OPD", "2,400", "Posted"],
      ["Pharmacy", "1,800", "Posted"],
      ["Pathology", "1,900", "Pending"],
      ["Radiology", "1,300", "Posted"],
    ],
    notes: ["Billing", "Collection", "Ledger update", "Daily close"],
    board: [
      { label: "Payment mode", items: ["Cash", "Card", "Bkash / Nagad"] },
      { label: "Ledger", items: ["Today receipts", "Pending dues", "Adjustments"] },
      { label: "Closing", items: ["Verify totals", "Approve entries", "Finalize sheet"] },
    ],
    summary: [
      { label: "Cash hand", value: "24,820" },
      { label: "Bank transfer", value: "0" },
      { label: "Outstanding", value: "1,200" },
    ],
  },
  reports: {
    title: "Reports",
    subtitle: "A quick entry point to operational and financial reports.",
    icon: FileText,
    tone: "bg-[#dbeafe]",
    actions: ["Daily report", "Date filter", "Download PDF", "Share summary"],
    stats: [
      { label: "Reports Today", value: "9", note: "generated" },
      { label: "Pending", value: "3", note: "to review" },
      { label: "Shared", value: "14", note: "downloaded" },
    ],
    columns: ["Report", "Department", "Status"],
    rows: [
      ["Daily collection", "Finance", "Ready"],
      ["Pending pathology", "Lab", "Draft"],
      ["Admission summary", "IPD", "Ready"],
      ["Medicine stock", "Pharmacy", "Ready"],
    ],
    notes: ["Filter by department", "Choose date range", "Review draft", "Export PDF"],
    board: [
      { label: "Operational", items: ["Patient flow", "Doctor activity", "IPD occupancy"] },
      { label: "Clinical", items: ["Lab status", "Radiology queue", "Medicine stock"] },
      { label: "Finance", items: ["Collections", "Outstanding", "Ledger summary"] },
    ],
    summary: [
      { label: "Ready reports", value: "6" },
      { label: "Draft reports", value: "3" },
      { label: "Exported today", value: "14" },
    ],
  },
  bed: {
    title: "Bed Management",
    subtitle: "Bed availability and occupancy tracking.",
    icon: BedIcon,
    tone: "bg-[#cbd5e1]",
    stats: [
      { label: "Available", value: "4", note: "free beds" },
      { label: "Occupied", value: "10", note: "in use" },
      { label: "Cabins", value: "6", note: "reserved" },
    ],
    columns: ["Bed", "Type", "Status"],
    rows: [
      ["B-01", "General", "Occupied"],
      ["B-03", "Cabin", "Available"],
      ["B-05", "ICU", "Occupied"],
      ["B-08", "General", "Maintenance"],
    ],
    notes: ["Assign patient", "Track ward", "Discharge clean-up", "Vacancy update"],
  },
  patient: {
    title: "Patient",
    subtitle: "Static patient registry with admission-ready list.",
    icon: UserRound,
    tone: "bg-[#dcfce7]",
    stats: [
      { label: "Registered", value: "214", note: "total patients" },
      { label: "New Today", value: "14", note: "entries" },
      { label: "Admitted", value: "10", note: "current IPD" },
    ],
    formTitle: "Patient Registration",
    formFields: hospitalSystemBlueprint.patient.formFields,
    relations: hospitalSystemBlueprint.patient.relations,
    entrySteps: hospitalSystemBlueprint.patient.registrationFlow,
    queueSummary: hospitalSystemBlueprint.patient.visitStatus,
    columns: ["Patient", "Age", "Status"],
    rows: [
      ["Ayesha", "26", "OPD"],
      ["Rahim", "41", "Admitted"],
      ["Nabila", "33", "Discharged"],
      ["Shamim", "58", "Waiting"],
    ],
    notes: ["Registration", "History", "Visit queue", "Admission"],
    board: [
      { label: "New registration", items: ["Name, age, contact", "Assign patient ID"] },
      { label: "Visit status", items: ["OPD", "IPD", "Follow-up"] },
      { label: "Important flags", items: ["Allergy", "Emergency", "Insurance"] },
    ],
  },
  doctor: {
    title: "Doctor",
    subtitle: "Consultant roster and department assignment.",
    icon: Users,
    tone: "bg-[#ede9fe]",
    stats: [
      { label: "On Duty", value: "8", note: "today" },
      { label: "Consultants", value: "12", note: "active doctors" },
      { label: "Specialties", value: "6", note: "covered" },
    ],
    formTitle: "Doctor Profile",
    formFields: hospitalSystemBlueprint.doctor.formFields,
    relations: hospitalSystemBlueprint.doctor.relations,
    entrySteps: hospitalSystemBlueprint.doctor.rosterFlow,
    queueSummary: hospitalSystemBlueprint.doctor.dutySummary,
    columns: ["Doctor", "Specialty", "Shift"],
    rows: [
      ["Dr. Karim", "Medicine", "Morning"],
      ["Dr. Sultana", "Gynae", "Evening"],
      ["Dr. Rahman", "Surgery", "Night"],
      ["Dr. Hasan", "Cardiology", "Morning"],
    ],
    notes: ["Roster setup", "Consultation slots", "Ward rounds", "Leave planning"],
    board: [
      { label: "Active today", items: ["Dr. Karim", "Dr. Hasan", "Dr. Sultana"] },
      { label: "Specialities", items: ["Medicine", "Surgery", "Cardiology"] },
      { label: "Next actions", items: ["Assign token", "Start consult", "Update notes"] },
    ],
  },
  referral: {
    title: "Referral",
    subtitle: "Outgoing and incoming referral tracking.",
    icon: ArrowRightLeft,
    tone: "bg-[#fef3c7]",
    stats: [
      { label: "Outgoing", value: "5", note: "this week" },
      { label: "Incoming", value: "7", note: "received" },
      { label: "Closed", value: "9", note: "completed" },
    ],
    columns: ["Case", "From", "To"],
    rows: [
      ["Cardiology", "OPD", "Dhaka Med"],
      ["Ortho", "IPD", "City Hospital"],
      ["Neuro", "ER", "Apollo"],
      ["ENT", "OPD", "Square"],
    ],
    notes: ["Case review", "Send summary", "Track response", "Close referral"],
  },
  "hr-payroll": {
    title: "HR & Payroll",
    subtitle: "Staff list, attendance, and payroll preparation.",
    icon: BookText,
    tone: "bg-[#dbeafe]",
    stats: [
      { label: "Employees", value: "54", note: "staff count" },
      { label: "Present", value: "49", note: "today" },
      { label: "Payroll", value: "Ready", note: "draft batch" },
    ],
    columns: ["Employee", "Role", "Status"],
    rows: [
      ["Nusrat", "Nurse", "Present"],
      ["Faruk", "Accountant", "Present"],
      ["Rina", "Reception", "Leave"],
      ["Kamal", "Support", "Present"],
    ],
    notes: ["Attendance", "Salary draft", "Overtime", "Finalize payroll"],
  },
  settings: {
    title: "Settings",
    subtitle: "System preferences and configuration placeholders.",
    icon: Settings,
    tone: "bg-[#e2e8f0]",
    stats: [
      { label: "Users", value: "1", note: "demo admin" },
      { label: "Modules", value: "18", note: "enabled" },
      { label: "Theme", value: "Light", note: "default" },
    ],
    columns: ["Setting", "Value", "Scope"],
    rows: [
      ["Organization", "Hospital management", "Global"],
      ["Timezone", "Asia/Dhaka", "Global"],
      ["Currency", "BDT", "Finance"],
      ["Language", "English", "UI"],
    ],
    notes: ["Profile", "Branding", "Permissions", "Security"],
  },
};

export function getModuleConfig(slug) {
  return moduleConfigs[slug] ?? null;
}
